version: '3.9'
name: 'mysql'
services:
  mysql:
    restart: always
    image: mysql:latest
    container_name: ${CONTAINER_NAME}
    volumes:
      - ${BASE_PATH}/mysql/:/mydir
      - ${BASE_PATH}/mysql/datadir:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf
    ports:
      - '${CONTAINER_PORT}:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
